### ISSUE TITLE
Need guideline/help

### ISSUE THREAD

**Issue by Pho3niX90** [pires/android-obd-reader#131] opened 2015-07-28 11:45 UTC
I am using a different obd2 reader to test commands on more cars, but I am having an issue where all info returned is incorrect.

For example please see attached image
What could the cause be?

![unnamed](https://cloud.githubusercontent.com/assets/7858187/8930506/ef1cdfc4-352e-11e5-86f9-21db1ae82562.png)

**Comment by Pho3niX90** [comment] 2015-07-28 11:46
The car was stationary. So non of those readings are correct.

**Comment by Pho3niX90** [comment] 2015-07-28 16:32
Here is a screenshot from terminal

![screenshot_2015-07-28-18-14-11](https://cloud.githubusercontent.com/assets/7858187/8937148/ff6ceacc-3556-11e5-9d13-9c139701c2b6.png)

**Comment by MaxBenChrist** [comment] 2015-07-28 22:09
You tried to restart the app? I mean by closing it the app settings in the general android menu?

I observed a similar behavior when I stopped the engine during a trip and the bt connection to the doongle was lost. The application was not able to connect again and when I started a new trip (even with a stationary car) it read 80 km/h and 167 rpm all the time.

For me killing the application in the menu and starting it again helped.

**Comment by pires** [comment] 2015-07-28 22:14
This is probably caused by the service not being able to reset/restart.

**Comment by MaxBenChrist** [comment] 2015-07-28 22:17
Yeah, I was thinking the same. You got any idea how to fix that properly? Maybe the trip should be finished if for a certain number of readings no values were observed?

**Comment by Pho3niX90** [comment] 2015-07-29 09:58
Fixed it.

**Comment by pires** [comment] 2015-07-29 10:05
How was it fixed?

**Comment by Pho3niX90** [comment] 2015-07-29 18:58
Seems that it isn't fixed. What I can gather is that for some dongles echo doesn't always turn off.

**Comment by sytolk** [comment] 2015-08-14 12:58
I have the same issue with my toyota corolla verso
![screenshot_2015-08-14-11-36-06](https://cloud.githubusercontent.com/assets/1415463/9274260/d81914b6-429c-11e5-9f24-f3efb3d07b70.png)

results is the same if car is moving or not. I have try to restart application restart Android phone but without success. @Pho3niX90 what is this terminal ?

**Comment by sytolk** [comment] 2015-09-09 13:56
09-09 16:43:20.520 E/com.github.pires.obd.reader.io.ObdGatewayService( 3354): Failed to run command. -> Error running 09 02, response: 0902NODATA

**Comment by sytolk** [comment] 2015-09-16 13:01
I have update obd-api lib to version 10. And test this issue with cheap but working with other obd app bluetooth hardware. The only changes are speed from 20km/h to 65 km/h but the real speed =0km/h
Its have trouble code true but the code is different..
![screenshot_2015-09-16-13-17-21](https://cloud.githubusercontent.com/assets/1415463/9905128/b3735334-5c8b-11e5-9791-b3b963fa35b3.png)

**Comment by Pho3niX90** [comment] 2015-09-16 13:59
@sytolk You are receiving echos. Some adapters require you to turn on echo and then off twice. Give that a try.

**Comment by Pho3niX90** [comment] 2015-09-16 14:00
@sytolk also make sure headers are off

**Comment by sytolk** [comment] 2015-09-16 15:20
I will try this. Thanks @Pho3niX90 But why these commands are not executed from obd-reader app?
https://www.scantool.net/support/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=32
ATE0 - Turn echo off. Characters sent to ElmScan are not retransmitted back to the host computer.
ATE1 - Turn echo on. This is the default state, characters are echoed back to the host computer.
ATH0 - Turn headers off. This is the default state, header information and CRC byte are omitted.
ATH1 - Turn headers on. Header information and CRC byte are displayed.
ATZ - Causes the chip to reset itself, as if the power was cycled off and then on again.

**Comment by Pho3niX90** [comment] 2015-09-16 15:27
@sytolk they are sent to turn of by default. But I have noticed on some dongles they need to be turned on and then off to correctly work.

**Comment by pires** [comment] 2015-12-08 15:30
@Pho3niX90 care to add latest comment to documentation?

**Closed** 2015-12-23 10:52 UTC
Labels: bug
